clc; clear;

nTrials = 100;
code = [];
preset = ['<div class=''trialDiv'' id=''trial_up1''>' ...
'<p><img src=''http://paulscotti.github.io/mturk/depth_scenes/scenes/scene101.jpg'' height=''200'' width=''200'' id=''trialImage1''/></p>' ...
'<input class=''slider'' name=''question1'' width=''200'' type=''range'' min=''1'' max=''100'' value=''50''/>' ...
	'<br>' ...
		'<div style=''float: left''>closer</div>' ...
		'<div style=''float: right''>farther</div>' ...
	'</br>' ...
'<div id=''circle_up''></div>' ...
'<center><br>' ...
	'<a href=''#'' class=''responseButton'' id=''nextButton''>Next</a>' ...
'</br></center></div>' ...
'<div class=''trialDiv'' id=''trial_down1''>' ...
'<p><img src=''http://paulscotti.github.io/mturk/depth_scenes/scenes/scene101.jpg'' height=''200'' width=''200'' id=''trialImage1''/></p>' ...
'<input class=''slider'' name=''question1'' width=''200'' type=''range'' min=''1'' max=''100'' value=''50''/>' ...
	'<br>' ...
		'<div style=''float: left''>closer</div>' ...
		'<div style=''float: right''>farther</div>' ...
	'</br>' ...
'<div id=''circle_down''></div>' ...
'<center><br>' ...
	'<a href=''#'' class=''responseButton'' id=''nextButton''>Next</a>' ...
'</br></center></div>'
];

for i = 1:100
    preset = strrep(preset,['trial_up',num2str(i-2)],['trial_up',num2str(i-1)]);
    preset = strrep(preset,['trial_down',num2str(i-2)],['trial_down',num2str(i-1)]);
    preset = strrep(preset,['scene',num2str(i+98)],['scene',num2str(i+99)]);
    preset = strrep(preset,['trialImage',num2str(i-2)],['trialImage',num2str(i-1)]);
    preset = strrep(preset,['question',num2str(i-2)],['question',num2str(i-1)]);
    code = strcat(code,preset);
end