clc; clear;

nTrials = 100;
code = [];
preset = ['<div class=''trialDiv'' id=''trial_up1''>' ...
'<p><img src=''http://paulscotti.github.io/mturk/depth_scenes/scenes/scene101.jpg'' height=''200'' width=''200'' id=''trialImage1''/></p>' ...
'<input class=''slider'' name=''question1'' width=''200'' type=''range'' min=''1'' max=''100'' value=''50''/>' ...
	'<br>' ...
		'<div style=''float: left''>closer</div>' ...
		'<div style=''float: right''>farther</div>' ...
	'</br>' ...
'<div id=''circle_up''></div>' ...
'<center><br>' ...
	'<a href=''#'' class=''responseButton'' id=''nextButton''>Next</a>' ...
'</br></center></div>' ...
'<div class=''trialDiv'' id=''trial_down1''>' ...
'<p><img src=''http://paulscotti.github.io/mturk/depth_scenes/scenes/scene101.jpg'' height=''200'' width=''200'' id=''trialImage1''/></p>' ...
'<input class=''slider'' name=''question1'' width=''200'' type=''range'' min=''1'' max=''100'' value=''50''/>' ...
	'<br>' ...
		'<div style=''float: left''>closer</div>' ...
		'<div style=''float: right''>farther</div>' ...
	'</br>' ...
'<div id=''circle_down''></div>' ...
'<center><br>' ...
	'<a href=''#'' class=''responseButton'' id=''nextButton''>Next</a>' ...
'</br></center></div>'
];


clc; clear;

code = [];
preset = ['<img src="https://paulscotti.github.io/mturk/Cont_LTM_101_files/objects/Object.jpg">'];

for i = 1:354
    preset = strrep(preset,'Object',['Object',num2str(100+i)]);
    code = strcat(code,preset);
    preset = ['<img src="https://paulscotti.github.io/mturk/Cont_LTM_101_files/objects/Object.jpg">'];
end