nTrials = 100;
code = [];
preset = ['<div class=''trialDiv'' id=''trial1_up''>' ...
'<p><img src=''http://paulscotti.github.io/mturk/depth_scenes/scenes/scene101.jpg'' height=''200'' width=''200'' id=''trialImage1''/></p>' ...
'<input class=''slider'' name=''question1'' width=''200'' type=''range'' min=''1'' max=''100'' value=''50''/>' ...
	'<br>' ...
		'<div style=''float: left''>closer</div>' ...
		'<div style=''float: right''>farther</div>' ...
	'</br>' ...
'<div id=''circle_up''></div>' ...
'<center><br>' ...
	'<a href=''#'' class=''responseButton'' id=''nextButton''>Next</a>' ...
'</br></center></div>'];

for i = 1:200
    preset = strrep(preset,['trial',num2str(i)-1],['trial',num2str(i)]);
    preset = strrep(preset,['scene',num2str(i)+99],['scene',num2str(i)+100]);
    preset = strrep(preset,['trialImage',num2str(i)-1],['scene',num2str(i)]);
    preset = strrep(preset,['question',num2str(i)-1],['question',num2str(i)]);
    code = strcat(code,preset);
end