const numberDisplay = document.getElementById('number-display');
// const soundDisplay = document.getElementById('sound-display');
const answerDisplay = document.getElementById('answer-display');
const minNumberInput = document.getElementById('min-number'); // Get input element
const maxNumberInput = document.getElementById('max-number'); // Get input element
const setRangeButton = document.getElementById('set-range-button'); // Get button element
const pauseResumeButton = document.getElementById('pause-resume-button');

// Ben System List (Full List)
const benSystemList = {
"000": "Dr Seuss // Cat in the hat",
"001": "Suit // zero suit samus",
"002": "soon // red Yoshi egg about to hatch",
"003": "sumo wrestler",
"004": "Suer // Miles Edgeworth",
"005": "Sulu // George Takei (oh my..)",
"006": "Sugar // Survivor Gabon",
"007": "sukiyaki // japanese hot pot",
"008": "souffle // ice cream on top",
"009": "Superman",
"010": "Sasuke // Naruto",
"011": "satellite",
"012": "Santa",
"013": "Samus, w/suit",
"014": "Saw // Jigsaw white puppet red circle cheeks",
"015": "Sal // Impractical Jokers",
"016": "saga // Harry Potter",
"017": "Sakura // Naruto",
"018": "sapphire // blue gem",
"019": "Zapdos",
"020": "Sesame Street // Ernie",
"021": "set and match // Roger Federer",
"022": "Zen // Rocket league",
"023": "cement truck",
"024": "Sara, Mark's gf",
"025": "cell phone",
"026": "segway",
"027": "sex // Faye Reagan",
"028": "cephalopod // squid",
"029": "Sebastian Michelmann",
"030": "scissors",
"031": "sitar",
"032": "cinder block",
"033": "cymbal",
"034": "Pinsir",
"035": "Silver Surfer",
"036": "cigar cutter",
"037": "sickle",
"038": "sieve",
"039": "sibling // half-sister, KLK",
"040": "(flying) saucer",
"041": "sawtooth shark",
"042": "Sonic",
"043": "zombie, SE",
"044": "sergeant, TS",
"045": "salt shaker",
"046": "soggy cereal (Cheerios in bowl + milk)",
"047": "sock puppet",
"048": "soft, adj // Gossamer",
"049": "SOB // Sid, TS",
"050": "suspend, v // ghost rope, DKC 2",
"051": "soot // a smokestack",
"052": "angry sun, SM 3",
"053": "zum*** Gran, SW",
"054": "surfboard w/fin",
"055": "Sullivan, from Monsters Inc",
"056": "sug, like “slug” // Ithorian, SW",
"057": "suck, v // Count von Count, SS // “I vont to suck your blood.”",
"058": "suffer, v // man in the iron mask",
"059": "sub // submarine Yoshi",
"060": "sAs, like “safe\" or “save somebody” // a lifebuoy",
"061": "Satan // robot satan, FR",
"062": "Sans // Undertale",
"063": "same // twins, Simpsons",
"064": "“straight hair”, phonetic approximation // a hair straightener",
"065": "Sailor Moon",
"066": "Sega // Dreamcast console",
"067": "sacred // Tibetan prayer wheel",
"068": "safe",
"069": "saber",
"070": "Caesar, Gladiator",
"071": "seat // reclining chair w/foot rest that comes out",
"072": "Zinger, DKC 2",
"073": "sea monkey, FG // just one",
"074": "seer, MTG artwork",
"075": "Seel (Pokemon)",
"076": "seagull",
"077": "seek, v // triple red shell, Mario",
"078": "seafood (mussels, open, on rectangular plate)",
"079": "zebra",
"080": "size, n // Quadraxis, MP",
"081": "sight // Mr eye, SM 64",
"082": "sign // wet floor sign",
"083": "siamese twins, SB",
"084": "siren, fantasy artwork",
"085": "silo",
"086": "zygote // macroscopic mass of cells // Motion may include internal divisions.",
"087": "cyclops // giant depiction",
"088": "syphon",
"089": "cyborg, Treasure Planet",
"090": "so small // baby Groot",
"091": "so tiny // a pixie, HP",
"092": "Sony // PSP",
"093": "sewing machine",
"094": "soar, v // the black dragon from HTTYD",
"095": "soul // Moaning Myrtle, HP",
"096": "sOg*** super battle droid, SW",
"097": "soak // squirt gun",
"098": "sofa (red)",
"099": "sober, adj // clamp robot from FR sober // rust",
"100": "too slow // Slowbro",
"101": "toot // (simple) horn",
"102": "tuning fork",
"103": "tomb raider, Angelina Jolie",
"104": "tour // (female) soldier, no helmet // w/gun // Use actress who played in FATF (Letty).",
"105": "toolbox, large, on rollers",
"106": "toog*** pit droid, SW",
"107": "toucan",
"108": "two feet // GNK power droid, SW",
"109": "tube, SM",
"110": "tassel // graduation cap",
"111": "tattoo device",
"112": "tangerine",
"113": "tambourine",
"114": "tar*** tin image, DKC 3",
"115": "talent // sax",
"116": "tags // wooden, connected by small rope (See pic)",
"117": "tack, blue",
"118": "taffy (in wrapper)",
"119": "tablet // electronic device",
"120": "Tesla coil",
"121": "tetherball",
"122": "tent",
"123": "temperature // a thermometer",
"124": "terror // antagonist in Saw mask, Saw",
"125": "(huge) telescope, non-tripod stand",
"126": "teg*** hornoad, Metroid",
"127": "Texas // Sandy, SB",
"128": "teflon // a pan",
"129": "teb*** Sidoh, DN",
"130": "tis the season // Christmas lights",
"131": "tits // Titters, Simpsons",
"132": "Tin Man",
"133": "Timon (LK)",
"134": "Tyrannosaurus rex",
"135": "till, v // tilling machine",
"136": "Tigger",
"137": "Tick (superhero)",
"138": "Tiffany, contrived name // hick lady w/tied shirt, Simpsons",
"139": "Tibetan Mastiff",
"140": "toss up, v, YI // just the guy on the bottom",
"141": "teeter totter",
"142": "tongs",
"143": "Tom, T&J",
"144": "tar // tar pit, bubbling",
"145": "tall, adj // tall alien from SW",
"146": "toggle switch // part of a larger device, affecting next image in some way",
"147": "taco character from Sausage Party",
"148": "toffee",
"149": "tob*** mishap image",
"150": "tusks // a walrus",
"151": "King Tut",
"152": "tunnel // mine cart",
"153": "tumbleweed",
"154": "turtle, Melee stage",
"155": "telepathy // Charles Xavier, X-Men",
"156": "tugboat",
"157": "tuck (and roll) // armadillo boss from Mega Man",
"158": "tough, adj // iron knuckles",
"159": "tub // bathtub filled with water",
"160": "taser // arc + sound",
"161": "Mr Potato Head, TS",
"162": "tank",
"163": "tame, adj // large orangutan",
"164": "tailor, n / Edna, The Incredibles",
"165": "Tails, from Sonic",
"166": "tAg*** probe // mnemonic: (taking girl) Where are you taging me?!?!",
"167": "takeoff image, MP",
"168": "take flight // Rocky the squirrel",
"169": "table",
"170": "tease, v // cat, SE",
"171": "teeth // windup teeth (w/feet), TS",
"172": "Tinker Bell",
"173": "team // Team Rocket, minus Meowth",
"174": "tear // bird crying, HP",
"175": "teal, color // Wynaut",
"176": "Tegan, contrived name // model for image from Ants (the princess)",
"177": "tiki-themed islander",
"178": "TV (CRT)",
"179": "tea bag",
"180": "Triceratops",
"181": "titan",
"182": "tiny goblin, fantasy artwork",
"183": "timer",
"184": "tire, DKC",
"185": "tile // Japanese Mahjong game tile // 中 tile",
"186": "tiger",
"187": "Tycoon // roller coaster",
"188": "tie fighter, SW",
"189": "tie beam // a gazebo, structural reference",
"190": "toaster",
"191": "totem // MP shrine",
"192": "(s)tone // incise image, YI",
"193": "tome // book from SM 64",
"194": "Thor, Greek god, no hammer",
"195": "troll // a troll from the movie Trolls",
"196": "Togepi",
"197": "token // DK coin",
"198": "tofu // tofu burger",
"199": "autobomb, SM 2",
"200": "noose, w/stand",
"201": "newt",
"202": "noonal // alien from FG alien erection joke",
"203": "pneumatic, adj // air compressor",
"204": "newer, adj // newer depiction of a classic Mario enemy",
"205": "new xylophone",
"206": "noog*** neuron, YS // mnemonic: He's the new guy",
"207": "nuke // motion: exploding",
"208": "new frontier // Deep Space Nine shuttle, ST // stationed by a newly discovered wormhole, hence new frontier",
"209": "Anubis",
"210": "NASA // guy in astronaut suit",
"211": "gnats, several",
"212": "nanny blooper",
"213": "Nami // One Piece",
"214": "Naruto",
"215": "nal*** wed droid, SW",
"216": "nag, v // Marge Simpson",
"217": "(nick)nack = mnemonic // YS image",
"218": "navigate, v // compass",
"219": "nab, v // from YI // no egg",
"220": "Ness w/Mr Saturn",
"221": "net // butterfly net",
"222": "nen*** FX medical droid, SW",
"223": "Nemesis, Resident Evil",
"224": "n-air // Kirby, Melee",
"225": "Snellie, SB",
"226": "negative, adj // Marvin the android, HGTTG",
"227": "necklace // diamond necklace",
"228": "never // (I’ve) never used this device. // rolling measuring device",
"229": "nebbish // cautious image (3)",
"230": "Princess Leia, SW",
"231": "knitting // The knitting can be autonomous or the result of an action. In either case, the result is a shawl, which can be worn by the next image.",
"232": "Ninji, SM 2",
"233": "Nymph",
"234": "Nirvana // the band member with blonde hair",
"235": "nil // toy w/rubber ball attached to paddle // nil = chances of having fun with this toy",
"236": "nigger // Uncle Ruckus, Boondocks",
"237": "nickel (coin)",
"238": "sniff, v // Barnacle Boy, SB // reference to large nose",
"239": "Nibbler, Futurama",
"240": "nozzle // FLUDD, SMS",
"241": "knot // a balloon animal",
"242": "Venonat",
"243": "nominee // Oscar trophy",
"244": "Narnia wardrobe, white",
"245": "knowledge // Socrates",
"246": "nog // eggnog carton",
"247": "knock, v // Buzzy beetle, Mario",
"248": "novice // Silver Rat driver",
"249": "knob // drawer // just one, knob on front, very fancy",
"250": "venus fly trap",
"251": "nut // walnut",
"252": "nun",
"253": "Numel",
"254": "nerd, Simpsons",
"255": "nullify (fantasy artwork)",
"256": "(gold) nugget",
"257": "Knuckles, Sonic",
"258": "Nruff, Kirby",
"259": "nub // robot from Futurama",
"260": "nasal spray",
"261": "native, SMS",
"262": "nAn*** the beetle from ABL",
"263": "name // Voldemort",
"264": "nutcr(A)cker // nutcracker",
"265": "nail clippers",
"266": "“That’s) no egg, it’s Exeggcute",
"267": "naked // mix image, FW",
"268": "navy // an anchor",
"269": "neighbor (from MNT)",
"270": "niece // Darla, FN, the dentist’s niece",
"271": "neat // a shelf",
"272": "Nina, fictional character // an angel",
"273": "Nemo, FN",
"274": "Near, DN",
"275": "Neil, FG",
"276": "knee gear // a knee dolly",
"277": "Neek, DKC 2",
"278": "Knievel // a ramp, both ends",
"279": "knee brace // Flash (superhero) wearing a knee brace (apparently after an injury)",
"280": "(enchanted/animated) nightstand, BATB",
"281": "knight",
"282": "Ninetales",
"283": "nightmare // TNBC main villain",
"284": "night rod",
"285": "nylon rope",
"286": "nightgown // Rem, Zero",
"287": "Nike // pair of Nike shoes",
"288": "knife",
"289": "night-blooming cactus",
"290": "nose // statue enemy from Super Mario Land",
"291": "note, SM 3",
"292": "Unown",
"293": "gnome (w/long, pointy hat)",
"294": "“knower\" // gypsy, Simpsons",
"295": "(grassy) knoll, grass-type Pokemon on top: Leafeon",
"296": "Noguchi table",
"297": "Noki Noki Bay // horn image, SMS",
"298": "novum image (contrived bionic girl)",
"299": "noble, adj // samurai, no weapon",
"300": "moose // Bullwinkle",
"301": "mutate, v // radioactive waste",
"302": "moon, TLOZ",
"303": "moom*** Thala-Siren, SW",
"304": "moon worm // moon/space worm from SW",
"305": "mule, heavily loaded `",
"306": "moog*** Meatwad",
"307": "mook*** toyshop image",
"308": "move // a dolly (two wheels at base)",
"309": "moon boots // King Bob-omb wearing moon boots",
"310": "mask, TLOZ",
"311": "mat // folding tatami mat (motion: unfolding)",
"312": "Mantis, Kung Fu Panda",
"313": "mammoth, Ice Age",
"314": "Mark Scotti",
"315": "malice // Red Skull",
"316": "magnifying glass",
"317": "Mac computer (laptop)",
"318": "Maveric drone",
"319": "mab // Ostro, SM 2 // no shy guy",
"320": "message in a bottle",
"321": "Metal Mario",
"322": "Men (in Black) // MIB cockroach villain",
"323": "memoire // Cranky Kong",
"324": "Mary // St Mary (holy gowned woman holding a baby)",
"325": "melon, YS",
"326": "Mega Man",
"327": "Mechakoopa, SMW // Receives action by being wound up",
"328": "metal frame // an old-fashioned scale",
"329": "metal boss // Chill Penguin, Mega Man",
"330": "missile shell, DKC",
"331": "mitt (baseball)",
"332": "minion (little yellow guy)",
"333": "Mim(ba) (blue blargg, from YI)",
"334": "mirror",
"335": "Milde, YI",
"336": "MiG-21 (aircraft)",
"337": "Mickey Mouse",
"338": "millennium falcon",
"339": "MIB creature // See pic",
"340": "mosquito, ABL",
"341": "Mothim",
"342": "monster // Frankenstein",
"343": "Mom, Futurama",
"344": "Marth, Melee",
"345": "Molly the Border Collie",
"346": "Magmar",
"347": "mochtroid, Metroid",
"348": "mafia",
"349": "mob, SB // no torches",
"350": "Mustang w/hood scoop",
"351": "mutt // the tramp from LATT",
"352": "monkey // an Ukiki, YI",
"353": "mummy, fantasy depiction",
"354": "mermaid, MLM",
"355": "mulberry bush, fruit prominent",
"356": "mug, empty",
"357": "Muk",
"358": "muffin",
"359": "Mother Brain, Metroid",
"360": "mace, weapon",
"361": "mate // king, chess piece, fancy",
"362": "mayonnaise",
"363": "maim, v // Kudgel's club, DKC 2",
"364": "Mayor Cheese",
"365": "(house) mailbox, empty",
"366": "mechanical egg beater",
"367": "makeup kit",
"368": "Mayflower",
"369": "mailbox (big blue one)",
"370": "Misa Misa, DN",
"371": "meat // a ham",
"372": "mean, adj // Hopper, ABL",
"373": "meme // Admiral Ackbar: \"It's a trap!\"",
"374": "(3) meerkats // phonetically deviant",
"375": "meal // happy meal",
"376": "Migi, Parasyte",
"377": "meek, adj // dog character, TP",
"378": "meat freezer",
"379": "meatballs",
"380": "mice, LM",
"381": "might // All Might, MHA",
"382": "mine // large, spikes, chain",
"383": "Mr Mime",
"384": "Crocomire, Metroid",
"385": "Mylum***",
"386": "migraine medication sheet",
"387": "mic",
"388": "mIv = metroid hive, MP",
"389": "smiley balloon (See pic)",
"390": "Moses, bible",
"391": "motocross bike",
"392": "Mona Lisa, in frame",
"393": "Elmo Muppet",
"394": "mower // big, like those used for parks",
"395": "mole // Monty Mole",
"396": "Mowgli",
"397": "mocha // frappe de mocha, Starbucks",
"398": "morph ball, MP",
"399": "Moby Dick",
"400": "rooster (from cartoons)",
"401": "roots // Bellsprout",
"402": "(Chozo) ruins // statue // Can be stationary or walk, like in the game",
"403": "broom",
"404": "roor*** Bantha, SW",
"405": "ruler",
"406": "Ruger the Border Collie",
"407": "Ryuk",
"408": "Rufus, Kim Possible",
"409": "rubies",
"410": "raspberry",
"411": "Raticate",
"412": "Randall, Melee",
"413": "ram (animal)",
"414": "rar*** boga, SW",
"415": "Raltz",
"416": "rag (white)",
"417": "tennis racket",
"418": "raft",
"419": "rabbit (brown)",
"420": "rest // hammock",
"421": "pretzel",
"422": "wrench",
"423": "Rem // Re:Zero",
"424": "rare, adj // Mew",
"425": "relish (animate), Sausage Party // Use Honey Mustard as a model.",
"426": "regulator // a regulator assembly attached to a pipe system",
"427": "Rex, SMW",
"428": "ref, striped shirt",
"429": "rebel // Chewy, SW",
"430": "Chris Griffin",
"431": "rhythm // metronome // Next image moves to rhythm",
"432": "rinse, v //  sink + faucet // See pic",
"433": "rim (for a car)",
"434": "rir*** Colo Claw, SW / mnemonic: (r)i(r) = hooks on both sides",
"435": "drill",
"436": "drill rig",
"437": "Elrik, from FMA (younger brother)",
"438": "rivet gun",
"439": "ribs (food)",
"440": "Andross, SF",
"441": "rotten tomatoes",
"442": "Ronnie Coleman",
"443": "Romulan // a Romulan child, male",
"444": "Rarrr!!!! -Rex, TS",
"445": "rolling pin",
"446": "frog, YI",
"447": "rock // Thardus, MP",
"448": "trough",
"449": "ROB",
"450": "rust // a rusty boat (falling apart)",
"451": "rut // wagon",
"452": "run, v // treadmill",
"453": "rum // Captain JS",
"454": "rural // windmill, Melee",
"455": "barrel // DKC checkpoint barrel // Barrel broken by previous image",
"456": "rug // circular, designs",
"457": "rook, chess piece // texture like a castle",
"458": "rough, adj // electric sander",
"459": "rubber ducky",
"460": "race // guy who races Mario in SMS",
"461": "wraith // ringwraith, LOTR",
"462": "rainbow",
"463": "Rayman",
"464": "Rareware // Banjo and Kazooie",
"465": "rail // train, YI",
"466": "ray gun // from artwork",
"467": "rake, plastic, distinct from hoe",
"468": "Raven, YI",
"469": "rabies // animated dog foaming at mouth // Use the Looney Tunes bulldog as a model.",
"470": "Reese's peanut butter cups",
"471": "wreath",
"472": "ring, from LOTR, writing visible, glowing",
"473": "remote, like for an RC plane",
"474": "rear // upright position // Rhydon",
"475": "rod + reel",
"476": "regal, adj // a peacock",
"477": "Rekoil, DKC 2",
"478": "reef",
"479": "rebound // a basketball player, tall, black",
"480": "rice // bowl of white rice",
"481": "write, v // pen",
"482": "rhino // Rambi, DKC 2",
"483": "rhyme // Dr Seuss // Cat in the Hat",
"484": "dryer",
"485": "Riley, Boondocks",
"486": "“right guy” (for the job) and the “rock guy” // rock guy, TP",
"487": "trike",
"488": "rifle w/scope",
"489": "dry bones // action: falling apart",
"490": "rose // a red rose",
"491": "Rotom",
"492": "“Ron” -Akagi",
"493": "Roman // Russel Crowe, Gladiator",
"494": "roar // Cerberus",
"495": "roller // paint roller",
"496": "rogue // X-wing, from SW",
"497": "Roy Koopa Kid",
"498": "rover // lunar rover",
"499": "robot, MTG",
"500": "illusive, adj // Shadow Mario, SMS",
"501": "loot, n // (open) bag of gold coins in a small burlap sack",
"502": "Looney Tunes // Dodo, cartoon character",
"503": "luminoth, MP",
"504": "lure, n // a fishing lure",
"505": "Lulu, FF",
"506": "glue gun",
"507": "Luke, SW",
"508": "loofah",
"509": "lubricant // oil applicator w/black bulb",
"510": "lasso",
"511": "latte",
"512": "lantern",
"513": "lamp, Pixar",
"514": "lar*** Morbo, from Futurama",
"515": "lal*** Cyndaquil // mnemonic: They call him \"littel Al\"",
"516": "lag // FOD, Melee",
"517": "(B)lack Shadow",
"518": "laugh // Krusty the Clown, Simpsons",
"519": "lab // Dexter, Dexter’s Lab",
"520": "lesson (Mrs Puff)",
"521": "letter w/seal",
"522": "lens image, Metroid",
"523": "Lemon guy from Adventure Time",
"524": "clarinet",
"525": "lel*** klamber, SMS",
"526": "Lego man",
"527": "Electrode",
"528": "level (tool)",
"529": "Celebi",
"530": "lizard // komodo dragon",
"531": "Little Foot",
"532": "linen // full linen bag, like from BJ's",
"533": "limo",
"534": "little red guy // l-eye-sick image, MM",
"535": "lily pad(s) + flower",
"536": "Gligar",
"537": "lick, v // Lickitung",
"538": "forklift",
"539": "liberty // Statue of Liberty",
"540": "floss",
"541": "lotter // lotery draw machine",
"542": "lawn mower",
"543": "lama",
"544": "large fan // a blower",
"545": "lollipop",
"546": "log",
"547": "(combination) lock, numbers on bottom",
"548": "lava lamp",
"549": "lobster",
"550": "lust // mosquito girl from OPM // bloodlust + very feminine form",
"551": "gluttony // robot from FR",
"552": "(p)lunger",
"553": "lumberjack in overalls and beanie w/axe",
"554": "Lrrr",
"555": "lull, v // rocking crib, curved base",
"556": "luggage // a duffle bag, large, black",
"557": "luck // 4-leaf clover",
"558": "(g)loves // the self-playing piano from Coraline",
"559": "lovebirds (2)",
"560": "laser",
"561": "late // Rabbit, Alice",
"562": "lane // traffic cone",
"563": "flame chomp, SM 3",
"564": "layer(s) (Crustle)",
"565": "flail thingy, FG",
"566": "“legs”, 8 of them // the spider from ABL",
"567": "lake // Dorrie, SM 64",
"568": "Slave 1, SW",
"569": "labeler",
"570": "Lisa (Simpson)",
"571": "elite pirate, MP",
"572": "Link",
"573": "lemur (normal)",
"574": "King Lear // old king",
"575": "Leela from Futurama",
"576": "league // giant squid, emphasis on beak",
"577": "leak // wooden bucket full of water, leaking between slats",
"578": "Levi // Attack on Titan",
"579": "leaf blower",
"580": "slice of cheesecake",
"581": "light bulb",
"582": "lion",
"583": "lime // cut in half",
"584": "liar // Squealer, New World anime",
"585": "lilac laundry detergent",
"586": "ligation, reference to a medical experiment // Kang, alien, Simpsons",
"587": "Like like, TLOZ",
"588": "life // DKC extra life balloon(s)",
"589": "library // robot, MTG",
"590": "Lois Griffin",
"591": "lotus, SM 3",
"592": "lone // wolf",
"593": "lowmum*** image, YS",
"594": "lore // chozo, MP",
"595": "Lawliet // L, from DN // on feet, hanging over knees, thumb to mouth",
"596": "Logan, X-Men",
"597": "Loki, Thor",
"598": "loaf (of bread)",
"599": "lobe // a brain enemy from Futurama",
"600": "goose, Kung Fu Panda",
"601": "Exeggutor",
"602": "(Bowser) Junior",
"603": "(winged) goomba",
"604": "guru // the guy from \"The Love Guru\" in lotus position wearing turban",
"605": "Julie Golomb",
"606": "goog, baby sound // baby Goku, DBZ",
"607": "jukebox",
"608": "Goofy",
"609": "Goofy Goober guy, SB",
"610": "gas (in gas can)",
"611": "gatling gun",
"612": "Ganon, Melee",
"613": "gamble, v // routlette wheel",
"614": "gar // Gengar // phonetically deviant",
"615": "gallon // 5-gallon water jug w/water",
"616": "(baby) jaguar",
"617": "jackhammer",
"618": "gavel",
"619": "Jabba the Hutt",
"620": "Jess Irons",
"621": "jet",
"622": "generator",
"623": "gem // master emerald, Sonic",
"624": "chair, SM 64",
"625": "jellyfish, YS",
"626": "geg*** Your Royal Highness, SB",
"627": "gecko",
"628": "Jeff Probst // Survivor",
"629": "geb*** podova image, no spaceship, SM",
"630": "gizmo // a component from Tick Tock Clock, SM 64",
"631": "guitar, acoustic",
"632": "Gingerbread Man // Shrek",
"633": "EW Jim",
"634": "Gir, from IZ",
"635": "gills // fishman",
"636": "jigsaw (tool)",
"637": "Chicken, FG",
"638": "gift // wrapped, pretty",
"639": "gibbon, tan-colored",
"640": "jaws // jaws image, MP",
"641": "Goth // Raven Teen Titans",
"642": "gong",
"643": "chomp, YI",
"644": "jar, glass, w/jam",
"645": "Golem (Pokemon)",
"646": "goggles",
"647": "(colored) chalk",
"648": "\"jaw + fish\"",
"649": "goblet // golden w/gems",
"650": "Gus Hennings",
"651": "Guts, KLK",
"652": "(futuristic) gun, MIB",
"653": "gum // bubble gum // If possible, previous image blows bubble that pops onto next image.",
"654": "giraffe",
"655": "gull, YI",
"656": "Juggernaut",
"657": "Chuck Norris",
"658": "glove // Master Hand, Melee",
"659": "\"jubjub” // little furry Neopet",
"660": "chase // Phanto, SM 2",
"661": "gate // mask gate, SM 2",
"662": "chainsaw",
"663": "game // Operation",
"664": "“gayer”, adj // Puri-puri, OPM",
"665": "jail, small (See pic for inspiration)",
"666": "gay guy, FG",
"667": "Jake, contrived name // an alien from MIB",
"668": "gave, verb past tense // a small, handheld vacuum // “I never use it. Somebody just gave it to me.\"",
"669": "Gabriel (angel) // movie depiction",
"670": "geese // Canadian geese",
"671": "cheetah",
"672": "Genie, Aladdin",
"673": "Geemer, MP",
"674": "gear // a gear",
"675": "(con)geal, v //red  jello on plate",
"676": "gEg*** Gyarados",
"677": "geek // a Simpsons geek character",
"678": "(indian) chief",
"679": "gEb*** kowakian, SW",
"680": "geyser",
"681": "giant turtle // a leatherback",
"682": "giant clam, DKC",
"683": "wind chime",
"684": "gyroscope",
"685": "child // Shippo, Inuyasha",
"686": "giant goldfish",
"687": "Geico gecko",
"688": "giant fish // Big Bertha, SMW",
"689": "giant bong",
"690": "ghost // Casper",
"691": "goat",
"692": "Gon // Hunter x Hunter",
"693": "gumball machine",
"694": "gore // Jason w/bloody knife",
"695": "(hockey) goalie",
"696": "go go // Energizer Bunny, no drum",
"697": "Joker from Batman",
"698": "Gopher, WTP",
"699": "globe",
"700": "cuckoo clock, cartoon depiction",
"701": "Q-tips (in open container)",
"702": "raccoon",
"703": "koom, a little like \"honeycomb\" // the bee from the Cheerios commercials",
"704": "Coor's beer 6-pack",
"705": "the kool aid guy",
"706": "cougar",
"707": "cuckoo bird (cereal)",
"708": "cooling fan, handheld w/mister",
"709": "cube // a Rubix cube",
"710": "castle // NES Mario castle",
"711": "Cat from Alice",
"712": "cannon",
"713": "camera (w/flash)",
"714": "careen, v // bumber car // Also phonetic approximation of car",
"715": "calculator",
"716": "kago, Metroid",
"717": "cactus // Caccac, Mario",
"718": "calf // a brown calf w/a bell",
"719": "(taxi) cab, FZGX",
"720": "kes*** Lanturn",
"721": "kettle",
"722": "Ken Norman",
"723": "chemistry // erlenmeyer flask w/red liquid bubbling/foaming out",
"724": "carrot",
"725": "kelp // columns of kelp gently swaying",
"726": "keg // upright, spewing out beer",
"727": "kek*** Elekid",
"728": "Kefka, FF",
"729": "kettlebell",
"730": "Kiss, band member // tongue out",
"731": "kitten",
"732": "Kingler",
"733": "Kim Possible",
"734": "Kirin (monster)",
"735": "kill // Ryuko, KLK",
"736": "kig*** Pillsbury Doughboy",
"737": "kick, v // soccer ball",
"738": "Kif, Futurama",
"739": "kibble (in bag)",
"740": "costume // Boo, MI",
"741": "cotton candy",
"742": "(California) condor",
"743": "comet, large tail",
"744": "car // morphing car, from YI",
"745": "column",
"746": "Cogsworth, BATB",
"747": "(hissing) cockroach",
"748": "cough medicine // Robitussin w/measuring cup lid",
"749": "cob (corn)",
"750": "cusp // Dr Otto, Spiderman // structural reference to points on prosthesis",
"751": "cut // Kleever, DKC 2",
"752": "kung fu // Panda, KFP",
"753": "(horned) chameleon",
"754": "Kurapika // Hunter x Hunter",
"755": "colors // paint palette",
"756": "k-uh-g*** ronto, SW",
"757": "cookie",
"758": "cuffs",
"759": "(polar bear) cub",
"760": "case",
"761": "catering // a character (girl) from Wagnaria",
"762": "cane // candy cane",
"763": "(baby) caiman",
"764": "kAr, a bit like \"care\", suggesting something for a child // a jack in the box",
"765": "kale salad",
"766": "kAg, like cake // icing applicator",
"767": "cake // birthday cake, single layer w/candles",
"768": "cave // stalagmites (bottom)",
"769": "cables",
"770": "keys // several keys on a loop",
"771": "keytar",
"772": "King Boo",
"773": "kimono // woman in traditional kimono",
"774": "keyring // a throwing star keychain",
"775": "Killua // Hunter x Hunter",
"776": "kEg, a bit like “kick” // Hitmonlee",
"777": "key clip (also fight spinner)",
"778": "key fob // a high-tech BMW key fob",
"779": "keyboard",
"780": "kite spider",
"781": "kite",
"782": "kind, adj // female “avatar”, Avatar",
"783": "chimera, FMA",
"784": "chiropractor tool",
"785": "Kyle Landry (in suit)",
"786": "kIg*** TT-8L/Y, SW",
"787": "kayak",
"788": "archive // filing cabinet, full of files",
"789": "kite buggy",
"790": "coaster, DKC 2 // nobody on it",
"791": "coat // Kloak, DKC 2",
"792": "(pine)cone",
"793": "comb",
"794": "core // apple core",
"795": "coal (burning)",
"796": "kOg*** Amorbis, MP",
"797": "Coke (classic bottle)",
"798": "cove // hermit crab",
"799": "cobra // Arbok",
"800": "foosball table",
"801": "futon, unique from sofa",
"802": "funeral // closed casket",
"803": "perfume w/sprayer",
"804": "food roll // a meat food roll",
"805": "fool // court jester",
"806": "foog*** the red ghost from Luigi’s Mansion",
"807": "food character // the burrito from Sausage Party",
"808": "foof*** Cloudjin, YS",
"809": "foob*** Jumpluff",
"810": "fast, adj // Dash, TI",
"811": "Fat Albert",
"812": "fan // a large fan",
"813": "vampire // the vampire from Bloodlust",
"814": "Far far away, but phonetically different // wolf, Shrek",
"815": "Falco",
"816": "fag // gay guy from FG w/pink tied shirt",
"817": "vacuum",
"818": "Flaaffy",
"819": "fabric roll, stripes",
"820": "pheasant // Unfezant",
"821": "feather",
"822": "Venom",
"823": "fembot, Futurama",
"824": "ferris wheel",
"825": "Velma, SD // w/freckles",
"826": "feg*** Lairon",
"827": "Vector // Despicable Me",
"828": "fef*** Teehee BF, YS",
"829": "Febreze spray bottle",
"830": "Inviso, YS",
"831": "fit, v // Russian nesting dolls",
"832": "Finn, FG",
"833": "fimbriae // a macroscopic bacterium with rotating flagella // an object",
"834": "virile, adj // an ox from Zootopia",
"835": "villain, The Incredibles",
"836": "figure // Candy Kong",
"837": "Victreebel",
"838": "vivid, adj // snake boss, SM 2",
"839": "fib // Pinocchio",
"840": "fossil // living trilobite",
"841": "father // Zurg, spoof, TS",
"842": "faun, PL",
"843": "vomit, n // (if possible) Previous image vomits",
"844": "far (far away), SW reference // character w/snake-like appendage on head and two bulbous protrusions on forehead",
"845": "volcano",
"846": "fog image, DKC 2",
"847": "Fox",
"848": "Fawful, Mario",
"849": "Fobio // Dory, FN // She called Nemo Fobio",
"850": "fuzzy, YI",
"851": "foot // hot foot, SM",
"852": "funnel",
"853": "fumble // a football",
"854": "fur coat",
"855": "Vulcan (female)",
"856": "fuzzy guy // a giant, fuzzy, flying worm (See pic.)",
"857": "fuck, v // a dildo, pink, artificial looking",
"858": "fluff // YWW image (fluff) // (if possible) Previous image hits it, next image comes out.",
"859": "football head // Arnold, Hey Arnold",
"860": "vase, SM 2",
"861": "fate // Excalibur, SE",
"862": "fangs/Ferengi // Quark, ST",
"863": "fame // Faye Valentine, CBBB",
"864": "conveyor belt",
"865": "veil // Simpson character (teacher) in wedding dress",
"866": "vagrant, n // a vagrant elf (female), fantasy artwork",
"867": "fake // false minoshiro",
"868": "favorite // Yoshi",
"869": "fable (fantasy artwork)",
"870": "fees // stack of textbooks",
"871": "feet // Tweety",
"872": "Rainbow Phoenix (FZGX) racer, not driver",
"873": "femur",
"874": "fear // Freddy",
"875": "feel // Yoda--\"feel the force\"",
"876": "vegan // broccoli",
"877": "Rafiki, TLK",
"878": "Fifi, Minnie’s dog",
"879": "Feebas",
"880": "vice (tool, blue)",
"881": "fight // Frieza, DBZ",
"882": "(reaper) vine, MP",
"883": "flying machine, SMW",
"884": "fire // a fire snake from Mario",
"885": "file",
"886": "flying spaghetti monster",
"887": "viking (fantasy artwork)",
"888": "fife, SM 3",
"889": "vibe // creature from YS",
"890": "foes // hammer brothers, SM 3",
"891": "photoshoot // Zoolander",
"892": "phone (w/circular plate for dailing)",
"893": "foam // red foam noodle",
"894": "force // Samuel L Jackson, SW",
"895": "foal",
"896": "vogue, adj // the mom from KLK",
"897": "vocalist, SW",
"898": "fovea // eye doctor equipment (See pic)",
"899": "phobia // many small spiders",
"900": "booze // Jack Daniel’s",
"901": "Boots, Dora",
"902": "Boondocks // grandad, shirtless",
"903": "boomerang",
"904": "buoy",
"905": "bool*** Bulbasaur",
"906": "boogeyman // Oogie Boogie",
"907": "book*** Maromi, Paranoia Agent",
"908": "blue + falcon (racer image)",
"909": "boo blah, YI",
"910": "basket // a wicker basket, tall, cylindrical, w/lid",
"911": "Pat // Mom",
"912": "Bandit, YI",
"913": "Bam Bam",
"914": "barbecue // phonetically deviant",
"915": "ballerina, female",
"916": "bag // a Whole Foods bag",
"917": "backpack",
"918": "baffle, v // a magician, Pixar depiction (Add white gloves.)",
"919": "baboon",
"920": "best // Black Star, SE",
"921": "bet // poker chips",
"922": "Bender",
"923": "bemuse, v // Arkana (the conjurer), no hat, Yu-Gi-Oh",
"924": "bear",
"925": "bell (small)",
"926": "beggar, fantasy artwork (an alien)",
"927": "“beck and call\" // a hotel desk bell",
"928": "bevel square",
"929": "beb*** Squirtle",
"930": "biscotti (3) // chocolate w/nuts",
"931": "bit, n // drill bit",
"932": "bin // trash bin",
"933": "bimbo // Jillian, FG + handbag or something",
"934": "Birdo",
"935": "Bill Clinton, FG depiction // Naked?",
"936": "Big Bird, SS",
"937": "bikini // girl in black bikini",
"938": "Bigfoot, Goofy",
"939": "bib // baby fish w/bib, SB",
"940": "boss // MM dino boss",
"941": "Robotic Birdo",
"942": "bonfire",
"943": "bomb // bob-omb, SM 64",
"944": "gold bars",
"945": "ball // basketball",
"946": "boggle, v // rope of handkerchiefs // motion: If possible, pulled out from hand of previous image.",
"947": "(cardboard) box",
"948": "“boss + fan\" // charge image, MM",
"949": "Bob the Builder",
"950": "Buzz, TS",
"951": "butter",
"952": "bun // cinnamon bun",
"953": "Bumpty, YI",
"954": "burrito",
"955": "bull",
"956": "bug, NES Mario",
"957": "book // YS book",
"958": "(African) buffalo",
"959": "bubble(s) // bubble liquid + blowing tool",
"960": "baseball",
"961": "Batman",
"962": "Bane (villain)",
"963": "bAm, a little like “bam” // Cubone, no bone in hand",
"964": "bAr*** tauntaun, SW // mnemonic: It looks a little like a bear.",
"965": "bale, cotton",
"966": "bagel cut in half w/cream cheese",
"967": "bake, v // oven mit",
"968": "bAf*** Phantoon, Metroid",
"969": "(Boss) baby",
"970": "Beast, BATB",
"971": "beetle, DKC 2",
"972": "beanstalk, SM",
"973": "beam // I-beam",
"974": "beer // a pitcher of beer",
"975": "below (the surface) or bEl*** eel, SM 64 // mnemonic: Look out! He's BELow the surface",
"976": "beagle // specific image w/distinct patterns",
"977": "beak // giant prehistoric bird",
"978": "beaver, DKC",
"979": "BB’s (in container with spout)",
"980": "bison",
"981": "bite // Chomps Jr, DKC",
"982": "binder",
"983": "bIm*** reek, SW",
"984": "buyer // shopping basket",
"985": "Bile, Monsters Inc",
"986": "bygone // a brontosaurus, representing a long-ago period",
"987": "bike (bicycle)",
"988": "bivalve // a puddle spore, MP // a fictitious bivalve",
"989": "bible, cross on cover",
"990": "bows // large bows, tied onto next image",
"991": "boat, SMS",
"992": "bone dragon, YS",
"993": "bowman (fantasy artwork)",
"994": "boar",
"995": "bowl // dog bowl",
"996": "bogus // a teenage MNT",
"997": "bouquet",
"998": "bovine creature from SW // shaak",
"999": "Boba Fett"
};

function getBenSystemSound(number) {
    const digitSounds = {
        '0': ['s', 'oo'],
        '1': ['t', 'a'],
        '2': ['n', 'e'],
        '3': ['m', 'i'],
        '4': ['r', 'o'],
        '5': ['l', 'u'],
        '6': ['g/j', 'A'],
        '7': ['k', 'E'],
        '8': ['f/th', 'I'],
        '9': ['b', 'O'],
    };

    const digits = number.split('');
    let sound = '';

    for (let i = 0; i < digits.length; i++) {
        const digit = digits[i];
        const soundType = i % 2 === 0 ? 0 : 1; // 0 for consonant, 1 for vowel
        sound += digitSounds[digit][soundType] + (i < digits.length - 1 ? ', ' : '');
    }

    return sound;
}

function speakText(text) {
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.rate = 1.75; // Increase the speech rate (default is 1)
    speechSynthesis.speak(utterance);
}

let currentNumber;
let isSlideshowRunning = false; // Flag to track if the slideshow is running
let slideshowInterval; // Variable to hold the interval ID

// Minimum and maximum values for the random number
let minNumber = 0;
let maxNumber = 999;

// Array to store the last 5 numbers presented
let lastFiveNumbers = [];

function generateRandomNumber() {
    let newNumber;
    const rangeSize = maxNumber - minNumber + 1;

    if (rangeSize <= 5) {
        // If the range is too small, just generate a random number without checking for repeats
        newNumber = Math.floor(Math.random() * rangeSize + minNumber)
            .toString()
            .padStart(3, '0');
    } else {
        // If the range is large enough, ensure no repeats in the last 5
        do {
            newNumber = Math.floor(Math.random() * rangeSize + minNumber)
                .toString()
                .padStart(3, '0');
        } while (lastFiveNumbers.includes(newNumber));
    }

    currentNumber = newNumber;

    // Update the last five numbers array
    lastFiveNumbers.push(currentNumber);
    if (lastFiveNumbers.length > 5) {
        lastFiveNumbers.shift(); // Remove the oldest number
    }

    numberDisplay.textContent = currentNumber;
    // soundDisplay.textContent = `(${getBenSystemSound(currentNumber)})`;
    answerDisplay.textContent = '';
    speakText(currentNumber);
}

function showAnswer() {
    answerDisplay.textContent = benSystemList[currentNumber];
    speakText(benSystemList[currentNumber]); // Speak the answer
}

function startSlideshow() {
    if (!isSlideshowRunning) {
        isSlideshowRunning = true;
        generateRandomNumber();

        slideshowInterval = setInterval(() => {
            setTimeout(() => {
                showAnswer();
                setTimeout(() => {
                    generateRandomNumber();
                }, 1200);
            }, 1200);
        }, 6000);
        pauseResumeButton.textContent = "Pause";
    }
}

function stopSlideshow() {
    if (isSlideshowRunning) {
        isSlideshowRunning = false;
        clearInterval(slideshowInterval);
        speechSynthesis.cancel();
        pauseResumeButton.textContent = "Resume";
    }
}

pauseResumeButton.addEventListener('click', () => {
    if (isSlideshowRunning) {
        stopSlideshow();
    } else {
        startSlideshow();
    }
});

function setMinMaxNumbers() {
    const min = parseInt(minNumberInput.value);
    const max = parseInt(maxNumberInput.value);

    if (min >= 0 && max <= 999 && min < max) {
        minNumber = min;
        maxNumber = max;
        console.log(`Slideshow range set to: ${minNumber} - ${maxNumber}`);

        // Only restart slideshow if it's already running
        if (isSlideshowRunning) {
            stopSlideshow();
            startSlideshow();
        }
    } else {
        console.error('Invalid minimum or maximum number.');
    }
}

setRangeButton.addEventListener('click', setMinMaxNumbers);

startSlideshow();